function featureExtractionModule(parentWindow)
    parentWindow.Visible = 'off';
    featureWindow = uifigure('Name', '特征提取', 'WindowStyle', 'normal', 'Position', [100, 100, 800, 500]);
    axOriginal = uiaxes(featureWindow, ...
        'Position', [50, 150, 300, 300], ...
        'XTick', [], 'YTick', [], 'Box', 'on');
    axOriginal.Title.String = '原图';
    uibutton(featureWindow, ...
        'Text', '上传图片', ...
        'Position', [50, 50, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) uploadImage(axOriginal));
    uibutton(featureWindow, ...
        'Text', 'LBP特征提取', ...
        'Position', [200, 50, 150, 30], ...
        'ButtonPushedFcn', @(btn, event) lbpFeatureWindow(axOriginal, featureWindow));
    uibutton(featureWindow, ...
        'Text', 'HOG特征提取', ...
        'Position', [400, 50, 150, 30], ...
        'ButtonPushedFcn', @(btn, event) hogFeatureWindow(axOriginal, featureWindow));
    uibutton(featureWindow, ...
        'Text', '返回', ...
        'Position', [600, 50, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) goBack(parentWindow, featureWindow));
end
function uploadImage(axOriginal)
    [file, path] = uigetfile({'*.jpg;*.png;*.bmp', '图像文件 (*.jpg, *.png, *.bmp)'; '*.*', '所有文件 (*.*)'}, '选择图片');
    if isequal(file, 0)
        return;
    end
    img = imread(fullfile(path, file));
    imshow(img, 'Parent', axOriginal);
    axOriginal.Title.String = '原图';
    axOriginal.UserData = img;
end
function lbpFeatureWindow(axOriginal, parentWindow)
    if isempty(axOriginal.UserData)
        uialert(axOriginal.Parent, '请先上传图片！', '错误');
        return;
    end
    parentWindow.Visible = 'off';
    lbpWindow = uifigure('Name', 'LBP特征提取', 'WindowStyle', 'normal', 'Position', [100, 100, 800, 500]);
    axOriginalLBP = uiaxes(lbpWindow, ...
        'Position', [50, 150, 300, 300], ...
        'XTick', [], 'YTick', [], 'Box', 'on');
    axOriginalLBP.Title.String = '原图';
    imshow(axOriginal.UserData, 'Parent', axOriginalLBP);
    axResultLBP = uiaxes(lbpWindow, ...
        'Position', [450, 150, 300, 300], ...
        'XTick', [], 'YTick', [], 'Box', 'on');
    axResultLBP.Title.String = 'LBP特征';
    img = axOriginal.UserData;
    lbpHist = extractLBPFeaturesManual(img);
    bar(axResultLBP, lbpHist);
    uibutton(lbpWindow, ...
        'Text', '返回', ...
        'Position', [650, 50, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) goBack(parentWindow, lbpWindow));
end
function hogFeatureWindow(axOriginal, parentWindow)
    if isempty(axOriginal.UserData)
        uialert(axOriginal.Parent, '请先上传图片！', '错误');
        return;
    end
    parentWindow.Visible = 'off';
    hogWindow = uifigure('Name', 'HOG特征提取', 'WindowStyle', 'normal', 'Position', [100, 100, 800, 500]);
    axOriginalHOG = uiaxes(hogWindow, ...
        'Position', [50, 150, 300, 300], ...
        'XTick', [], 'YTick', [], 'Box', 'on');
    axOriginalHOG.Title.String = '原图';
    imshow(axOriginal.UserData, 'Parent', axOriginalHOG);
    axResultHOG = uiaxes(hogWindow, ...
        'Position', [450, 150, 300, 300], ...
        'XTick', [], 'YTick', [], 'Box', 'on');
    axResultHOG.Title.String = 'HOG特征';
    img = axOriginal.UserData;
    hogFeatures = extractHOGFeaturesManual(img);
    bar(axResultHOG, hogFeatures);
    uibutton(hogWindow, ...
        'Text', '返回', ...
        'Position', [650, 50, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) goBack(parentWindow, hogWindow));
end
function goBack(parentWindow, currentWindow)
    delete(currentWindow);
    parentWindow.Visible = 'on';
end
