function geometryTransformModule(parentWindow)
    parentWindow.Visible = 'off';
    transformWindow = uifigure('Name', '几何变换', 'WindowStyle', 'normal', 'Position', [100, 100, 800, 500]);
    axImage = uiaxes(transformWindow, ...
        'Position', [100, 150, 300, 300], ...
        'XTick', [], 'YTick', [], ...
        'Box', 'on');
    axImage.Title.String = '原始图像';
    uploadBtn = uibutton(transformWindow, ...
        'Text', '上传图片', ...
        'Position', [100, 50, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) uploadImage(axImage));
    scaleBtn = uibutton(transformWindow, ...
        'Text', '缩放', ...
        'Position', [250, 50, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) scaleImageModule(transformWindow, axImage));
    rotateBtn = uibutton(transformWindow, ...
        'Text', '旋转', ...
        'Position', [400, 50, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) rotateImageModule(transformWindow, axImage));
    backButton = uibutton(transformWindow, ...
        'Text', '返回', ...
        'Position', [550, 50, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) goBack(parentWindow, transformWindow));
end
function uploadImage(axImage)
    [file, path] = uigetfile({'*.jpg;*.png;*.bmp', '图像文件 (*.jpg, *.png, *.bmp)'; '*.*', '所有文件 (*.*)'}, ...
                             '选择一张图片');
    if isequal(file, 0)
        return;
    end
    img = imread(fullfile(path, file));
    imshow(img, 'Parent', axImage);
    axImage.Title.String = '原始图像';
    axImage.UserData = img;
end

function scaleImageModule(parentWindow, axImage)
    if isempty(axImage.UserData)
        uialert(axImage.Parent, '请先上传图片！', '错误');
        return;
    end
    img = axImage.UserData;
    parentWindow.Visible = 'off';
    scaleWindow = uifigure('Name', '缩放图像', 'WindowStyle', 'normal', 'Position', [100, 100, 800, 500]);
    axOriginal = uiaxes(scaleWindow, ...
        'Position', [50, 200, 300, 250], ...
        'XTick', [], 'YTick', [], ...
        'Box', 'on');
    imshow(img, 'Parent', axOriginal);
    axOriginal.Title.String = '原始图像';
    axScaled = uiaxes(scaleWindow, ...
        'Position', [400, 200, 300, 250], ...
        'XTick', [], 'YTick', [], ...
        'Box', 'on');
    axScaled.Title.String = '缩放后图像';
    lbl = uilabel(scaleWindow, ...
        'Text', '缩放比例 (0.1~3.0):', ...
        'Position', [50, 80, 150, 30]);
    scaleInput = uieditfield(scaleWindow, 'numeric', ...
        'Position', [200, 80, 100, 30], ...
        'Limits', [0.1, 3.0], ...
        'Value', 1.0);
    applyBtn = uibutton(scaleWindow, ...
        'Text', '应用缩放', ...
        'Position', [320, 80, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) applyScaling(img, scaleInput.Value, axScaled));
    backButton = uibutton(scaleWindow, ...
        'Text', '返回', ...
        'Position', [650, 50, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) goBack(parentWindow, scaleWindow));
end
function applyScaling(img, scaleFactor, axScaled)
    addpath('D:\Files\ProgramProject\MatLab\FinalWork\GUI\utils');
    scaledImg = manualImageScaling(img, scaleFactor);
    imshow(scaledImg, 'Parent', axScaled);
    axScaled.Title.String = sprintf('缩放后图像 (%.2fx)', scaleFactor);
end
function rotateImageModule(parentWindow, axImage)
    if isempty(axImage.UserData)
        uialert(axImage.Parent, '请先上传图片！', '错误');
        return;
    end
    img = axImage.UserData;
    parentWindow.Visible = 'off';
    rotateWindow = uifigure('Name', '旋转图像', 'WindowStyle', 'normal', 'Position', [100, 100, 800, 500]);
    axOriginal = uiaxes(rotateWindow, ...
        'Position', [50, 200, 300, 250], ...
        'XTick', [], 'YTick', [], ...
        'Box', 'on');
    imshow(img, 'Parent', axOriginal);
    axOriginal.Title.String = '原始图像';
    axRotated = uiaxes(rotateWindow, ...
        'Position', [400, 200, 300, 250], ...
        'XTick', [], 'YTick', [], ...
        'Box', 'on');
    axRotated.Title.String = '旋转后图像';
    lbl = uilabel(rotateWindow, ...
        'Text', '旋转角度 (-360~360):', ...
        'Position', [50, 80, 150, 30]);
    rotateInput = uieditfield(rotateWindow, 'numeric', ...
        'Position', [200, 80, 100, 30], ...
        'Limits', [-360, 360], ...
        'Value', 0);
    applyBtn = uibutton(rotateWindow, ...
        'Text', '应用旋转', ...
        'Position', [320, 80, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) applyRotation(img, rotateInput.Value, axRotated));
    backButton = uibutton(rotateWindow, ...
        'Text', '返回', ...
        'Position', [650, 50, 120, 30], ...
        'ButtonPushedFcn', @(btn, event) goBack(parentWindow, rotateWindow));
end
function applyRotation(img, angle, axRotated)
    addpath('D:\Files\ProgramProject\MatLab\FinalWork\GUI\utils');
    rotatedImg = manualImageRotation(img, angle);
    imshow(rotatedImg, 'Parent', axRotated);
    axRotated.Title.String = sprintf('旋转后图像 (%d°)', angle);
end
function goBack(parentWindow, currentWindow)
    delete(currentWindow);
    parentWindow.Visible = 'on';
end
