function mainWindow()
    homeWindow = uifigure('Name', '图像处理工具', 'WindowStyle', 'normal', 'Position', [100, 100, 640, 400]);
    histogramButton = uibutton(homeWindow, ...
        'Text', '直方图处理', ...
        'Position', [270, 240, 100, 50], ...
        'ButtonPushedFcn', @(btn, event) histogramModule(homeWindow));
    grayscaleButton = uibutton(homeWindow, ...
        'Text', '灰度化处理', ...
        'Position', [270, 180, 100, 50], ...
        'ButtonPushedFcn', @(btn, event) grayscaleModule(homeWindow));
    geometryButton = uibutton(homeWindow, ...
        'Text', '几何变换', ...
        'Position', [270, 120, 100, 50], ...
        'ButtonPushedFcn', @(btn, event) geometryTransformModule(homeWindow));
    exitButton = uibutton(homeWindow, ...
        'Text', '退出', ...
        'Position', [270, 60, 100, 50], ...
        'ButtonPushedFcn', @(btn, event) closeApp(homeWindow));
end
function closeApp(homeWindow)
    delete(homeWindow);
end
