function mainWindow()
    % 创建主窗口
    homeWindow = uifigure('Name', '图像处理工具', 'WindowStyle', 'normal', 'Position', [100, 100, 640, 400]);
    
    % 直方图处理按钮
    histogramButton = uibutton(homeWindow, ...
        'Text', '直方图处理', ...
        'Position', [270, 300, 100, 50], ...
        'ButtonPushedFcn', @(btn, event) histogramModule(homeWindow));
    
    % 灰度化处理按钮
    grayscaleButton = uibutton(homeWindow, ...
        'Text', '灰度化处理', ...
        'Position', [270, 240, 100, 50], ...
        'ButtonPushedFcn', @(btn, event) grayscaleModule(homeWindow));
    
    % 几何变换按钮
    geometryButton = uibutton(homeWindow, ...
        'Text', '几何变换', ...
        'Position', [270, 180, 100, 50], ...
        'ButtonPushedFcn', @(btn, event) geometryTransformModule(homeWindow));
    
    % 噪声与滤波按钮
    noiseFilterButton = uibutton(homeWindow, ...
        'Text', '噪声与滤波', ...
        'Position', [270, 120, 100, 50], ...
        'ButtonPushedFcn', @(btn, event) noiseFilterModule(homeWindow));
    
    % 退出按钮
    exitButton = uibutton(homeWindow, ...
        'Text', '退出', ...
        'Position', [270, 60, 100, 50], ...
        'ButtonPushedFcn', @(btn, event) closeApp(homeWindow));
end

function closeApp(homeWindow)
    % 关闭主窗口
    delete(homeWindow);
end
