function mainWindow()
    homeWindow = uifigure('Name', '图像处理工具', 'WindowStyle', 'normal', 'Position', [100, 100, 640, 400]);
    histogramButton = uibutton(homeWindow, ...
        'Text', '直方图处理', ...
        'Position', [270, 180, 100, 50], ...
        'ButtonPushedFcn', @(btn, event) histogramModule(homeWindow));
end